---
version: '2'

services:

  katalod:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: pdnd-semantic-katalod
    image: teamdigitale/pdnd-semantic-katalod
    environment:
      VERS: "0.0.11"
    stdin_open: true
    tty: true
    ports:
      - 7777:7777/tcp
